---
#first Ansible playbook
- hosts: local
  vars:
    hostname: bswitch1
   
  tasks:
    - name: Generate 5 switch configs
      template: src=/Users/bbooher/pynet_testz/class5/access_switch-ex1.j2 dest=/Users/bbooher/pynet_testz/class5/CFGS/bswitch1.txt
