[mylocal]
localhost ansible_connection=local

[devwww]
dev_www1 ansible_ssh_host=10.10.1.1 ansible_ssh_user=webadmin
dev_www2 ansible_ssh_host=10.10.1.2 ansible_ssh_user=webadmin
dev_www3 ansible_ssh_host=10.10.1.3 ansible_ssh_user=webadmin
dev_www4 ansible_ssh_host=10.10.1.4 ansible_ssh_user=webadmin
dev_www5 ansible_ssh_host=10.10.1.5 ansible_ssh_user=webadmin

[testnew]
test1 ansible_ssh_host=10.250.0.10 ansible_ssh_user=gituser ansible_ssh_port=8022

[pynetrtr]
pynetrtr1 ansible_ssh_host=184.105.247.70 ansible_ssh_user=pyclass ansible_ssh_port=22
pynetrtr2 ansible_ssh_host=184.105.247.71 ansible_ssh_user=pyclass ansible_ssh_port=22

[pynetsw]
pynetsw1 ansible_ssh_host=184.105.247.72 ansible_ssh_user=admin1 ansible_ssh_port=22
pynetsw2 ansible_ssh_host=184.105.247.73 ansible_ssh_user=admin1 ansible_ssh_port=22
pynetsw3 ansible_ssh_host=184.105.247.74 ansible_ssh_user=admin1 ansible_ssh_port=22
pynetsw4 ansible_ssh_host=184.105.247.75 ansible_ssh_user=admin1 ansible_ssh_port=22

[pynetjnprsrx]
pynetjnprsrx1 ansible_ssh_host=184.105.247.76 ansible_ssh_user=pyclass ansible_ssh_port=22
