---
- name: Arista Ansible scripts exercise 2
  hosts: arista
  tasks:
    - name: Modify Ethernet5 description
      eos_interface: name=Ethernet5
            description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
    - name: Modify Ethernet5 mode
      eos_switchport: name=Ethernet5
            mode=access
            access_vlan=666
            username={{ eapi_username }} 
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
