#!/usr/bin/env python
'''Script uses Netmiko to connect to router and enter config mode
Please note. This script looks just like yours, but that was after I tried
to take one of my previous scripts and keep the extended dictionary entries I had.
it would seem that Netmiko does extensive error checking on the dictionaries
to make sure the values are appropriate. '''

#### import statements
from netmiko import ConnectHandler
from device_list import A_DEVICE_LIST

# main function (this is the main execution code for your program)
def main():
    '''Main function, opens connection, enters config mode and verifies'''
    for a_device in A_DEVICE_LIST:
        a_connection = ConnectHandler(**a_device)
        outp = a_connection.send_command("show arp")
        print outp

if __name__ == "__main__":                    # program execution starts here
    main()                                                   # first action is to call main function
